[programs.localnet]
chicken = "x1UTZfeybkzAzTHZxswXBvyLMk3drMNQGsrBMmYtCSN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
